### ISSUE TITLE
Error building moira-cache

### ISSUE THREAD

**Issue by ymrsmns** [warmfusion/moira-docker#3]
docker-compose up
Building moira-cache
Step 1/5 : FROM golang:1.7
 ---> 225948c9a8b1
Step 2/5 : ENV GOPATH /moira
 ---> Using cache
 ---> e56cf7c66d23
Step 3/5 : RUN go get github.com/moira-alert/cache
 ---> Running in c49d0ef5e30f
package menteslibres.net/gosexy/dig: unrecognized import path "menteslibres.net/gosexy/dig" (parse https://menteslibres.net/gosexy/dig?go-get=1: no go-import meta tags)
ERROR: Service 'moira-cache' failed to build: The command '/bin/sh -c go get github.com/moira-alert/cache' returned a non-zero code: 1

https://menteslibres.net/gosexy/dig - return 502 error

**Comment by gecube** [comment]
I confirm this issue.

**Comment by warmfusion** [comment]
Since the original creation of this project, moira has adopted its own implementation of containerised builds.

Please refer to https://github.com/moira-alert/moira on how to use their own managed docker ecosystem maintained by the upstream project.
